import {esc, toCSV} from "./format.js";
export function servicesHTML(r, opts={}){
 if(!opts.provider) return servicesHTML(r,{...opts,provider:"Shodan"});
 if(!r.service_observations) return "";
 const s=r.service_observations;
 const provider=opts.provider;
 return `<section class="block" data-service-provider="${provider.toLowerCase()}"><h2>Public service observations${provider!=="Shodan" ? ` · ${provider}` : ""}</h2><p>Source: ${provider}. Existing observations, separate from routing evidence. These records do not establish current exposure or system ownership.</p><p class="hint">${esc(s.limits || "")}</p>${(s.records || []).map((x,n)=>{const index=provider!=="Shodan" ? `${provider.toLowerCase()}-${n}` : n;return `<h3>${esc(x.resource)} · ${esc(x.status)}</h3><p class="hint">Query: ${esc(x.query)}. Retrieved: ${esc(x.retrieved_at || "not available")}. Source total: ${esc(x.total ?? "unknown")}${x.total_unit ? ` ${esc(x.total_unit)}` : ""}. ${x.coverage_unknown ? "Service coverage is incomplete or unknown." : ""} ${x.additional_pages_possible ? "Another source page may be available." : ""} ${x.truncated ? `More ${provider} records remain unfetched.` : ""} ${x.rejected_records ? `${esc(x.rejected_records)} malformed or out-of-scope records excluded.` : ""}</p>${x.error ? `<p>${esc(x.error)}</p>` : ""}<p class="hint">${esc(x.services?.length || 0)} service records retained. ${(x.page_sources || []).map(p=>`Source page ${esc(p.page)} retrieved ${esc(p.retrieved_at)} (${esc(p.returned)} ${esc(p.unit || "records")})`).join("; ")}</p>${x.services?.length ? `<div class="tablewrap"><table><thead><tr><th>IP</th><th>Port / transport</th><th>Service</th><th>${provider} observation time</th></tr></thead><tbody>${x.services.map((v,i)=>serviceRow(v,index,i,{...opts,provider})).join("")}</tbody></table></div>` : `<p>No service records retained. This does not prove there are no exposed services.</p>`}${opts.interactive && x.status !== "failed" && (x.services?.length || x.truncated || x.additional_pages_possible) ? `<nav class="service-pages no-print" data-service-nav="${index}" aria-label="Service result pages for ${esc(x.resource)}"></nav><p class="no-print" data-service-message="${index}" role="status"></p>` : ""}`;}).join("")}<p>Review with the system owner: do we expect these services to be publicly accessible?</p></section>`;
}

export function servicesCSV(r){
 return toCSV(["resource","status","source","retrieved_at","source_total","source_total_unit","truncated","rejected_records","ip","port","transport","service","observed_at","source_record_id","host","path","timestamp_basis","error"],(r.service_observations?.records || []).flatMap(x=>(x.services?.length ? x.services : [{}]).map(v=>[x.resource,x.status,x.source,x.retrieved_at,x.total,x.total_unit || "service records",x.truncated,x.rejected_records,v.ip,v.port,v.transport,v.service,v.observed_at,v.source_record_id,v.host,v.path,v.timestamp_basis,x.error])));
}

function serviceRow(v,index,i,opts){
 const id=`service-detail-${index}-${i}`;
 const d=v.details || {};
 const value=x=>x == null || x === "" || (Array.isArray(x) && !x.length) ? "Not reported" : Array.isArray(x) ? x.join(", ") : x;
 const dn=x=>x && typeof x==="object" && Object.keys(x).length ? Object.entries(x).map(([k,v])=>`${k}: ${v}`).join(", ") : "Not reported";
 const fields=[["Recorded host",v.host],["Recorded path",v.path],["Timestamp basis",v.timestamp_basis],["Product",d.product],["Version",d.version],["Hostnames",d.hostnames],["Domains",d.domains],["HTTP title",d.http_title],["HTTP server",d.http_server],[`${opts.provider || "Shodan"}-reported organization`,d.organization],[`${opts.provider || "Shodan"}-reported ISP`,d.isp],[`${opts.provider || "Shodan"}-reported ASN`,d.asn],["TLS subject",dn(d.tls_subject)],["TLS issuer",dn(d.tls_issuer)],["TLS issued (as reported)",d.tls_issued],["TLS expiry (as reported)",d.tls_expires]];
 return `<tr ${opts.interactive ? `data-service-row="${index}" data-row="${i}"` : ""}><td>${opts.interactive ? `<button type="button" class="service-disclosure" aria-expanded="false" aria-controls="${id}" aria-label="Service details for ${esc(v.ip)} port ${esc(v.port)} ${esc(v.transport)}"><span aria-hidden="true">▸</span></button>` : ""}${esc(v.ip)}</td><td>${esc(v.port)} / ${esc(v.transport)}</td><td>${esc(v.service)}</td><td>${esc(v.observed_at || "Not supplied")}</td></tr>
 <tr id="${id}" ${opts.interactive ? `data-service-detail="${index}" data-row="${i}" hidden` : ""}><td colspan="4"><div class="service-details"><h4>Service details: ${esc(v.ip)} · ${esc(v.port)} / ${esc(v.transport)}</h4><p class="hint">${opts.provider || "Shodan"}-reported fields from this service observation. Missing fields are not evidence of absence. Collection module: ${esc(v.service)}.</p><dl>${fields.map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(value(v))}</dd>`).join("")}</dl><h4>Recorded service banner</h4><pre>${esc(value(d.banner))}</pre>${d.banner_truncated ? "<p class=hint>Banner truncated to 2,048 characters.</p>" : ""}</div></td></tr>`;
}
