"""Generate factual operator limits from the application's configuration."""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from pathfinder import config

TARGET = Path(__file__).resolve().parents[1] / "docs/LIMITS.md"
ITEMS = [
    ("Footprint entries", "MAX_FOOTPRINT_ROWS", "distinct public IPs or prefixes"),
    ("Footprint upload", "MAX_UPLOAD_BYTES", "bytes"),
    ("Saved report import", "MAX_IMPORT_BYTES", "bytes"),
    ("Source response", "MAX_RESPONSE_BYTES", "bytes per response"),
    ("Per-run cache", "MAX_CACHE_BYTES", "serialized JSON bytes; object overhead is additional"),
    ("Footprint resolution", "MAX_RESOLVE_LOOKUPS", "source lookups"),
    ("Prefix expansion", "MAX_RANGE_EXPANSION", "more-specifics per entry"),
    ("Confirmed ASNs", "MAX_CONFIRMED_ASNS", "per adjacency run"),
    ("BGP processing", "MAX_AS_ROUTES", "source route records"),
    ("BGP export subset", "MAX_CP_PATHS_KEPT", "retained path records"),
    ("Run retention", "JOB_TTL_SECONDS", "seconds after completion; capacity may evict sooner"),
    ("Run capacity", "MAX_JOBS", "stored runs; at most two active"),
]
text = "# Configured limits\n\nGenerated by `python3 tools/gen_limits.py`.\n\n| Boundary | Limit | Meaning |\n| --- | ---: | --- |\n"
for label, name, meaning in ITEMS:
    text += f"| {label} | {getattr(config, name):,} | {meaning} |\n"
if "--check" in sys.argv:
    if not TARGET.exists() or TARGET.read_text() != text:
        raise SystemExit("Limits documentation is out of date. Run tools/gen_limits.py.")
else:
    TARGET.write_text(text)
